### ISSUE TITLE
BEL support inadvertently dropped in 0.6.0 

### ISSUE THREAD

**Issue by durbanlegend** [dalance/termbg#30]
I must apologise that my PR for issue #25 inadvertently dropped the check for the BEL string terminator. This came to my attention when working in Apple Terminal in MacOS.

This started me looking more closely into Xterm string terminators, and I realise that the issue is less straightforward than I supposed.  For instance, the relevant standard (ECMA 48) specifies ST as 0x9c or Esc 0x5c (Esc \). Some Xterm emulators will map Esc \ to the single key event Alt-\\. Similarly BEL 0x07 may be mapped to Ctrl-g, or it may not. Xterm recognises both 7-bit (C0) and 8-bit (C1) control sequences. So anticipating the terminators for different platforms unfortunately involves some guesswork.
This prompted me to try to make interpreting the OSC 11 response less dependent on recognising the terminator. In the version I'm using in my project, I've done the following:
1. Anticipated additional possible mappings of the terminators.
2. Where no recognised terminator is received, check the response string before timing out, and accept a valid r/g/b response irrespective of the terminator or the absence of a recognised terminator.
3. Debugging aids:
a. Add a --debug / -d option to the `termbg` command to facilitate interactive testing. This will initialise a `simplelog` terminal logger in debug mode that will display the debug! statements to the terminal. Importantly, it will not change the default behaviour.
b. Add more debug! statements, e.g. to show discarded key events that may be unrecognised terminators.
c. End all debug! statements with a carriage return (CR = \r) because when we set the terminal to raw mode it switches off the normal mapping of line feed (LF = \n) to CR LF, so that CRs are not generated and output lines start at the end position of the previous line instead of at position 0, making output difficult to read.
These changes have allowed me to do a lot more effective interactive testing on different terminals in MacOS,Windows and Linux.
4.  Unit tests. Saving the best tilI last, I've finally introduced unit tests for OSC 11 queries, testing the different anticipated scenarios namely:
a. Various mappings and interpretations of ST and BEL
b. Unrecognised and missing terminators
c. Incomplete responses
d. Missing response.

However, I don't want to impose my changes on your project. So I have 2 alternative PRs in preparation for you to consider:
1. A PR with minimal changes, to correct my previous mistake.
2. A maximal PR with all my changes.

I'll put them up soon. Please have a look when you can and see what you prefer to do.

Once again, apologies for the oversight on my part.

Regards,
Don

References:
https://www.xfree86.org/4.8.0/ctlseqs.html
https://www.ecma-international.org/wp-content/uploads/ECMA-48_5th_edition_june_1991.pdf
https://xtermjs.org/docs/api/vtfeatures/

**Comment by dalance** [comment]
Thank you for your detailed information.
I want to merge your maximal PR, and I'll check it in this week.

**Comment by durbanlegend** [comment]
Many thanks! Apologies again for the inconvenience.

**Comment by dalance** [comment]
I released v0.6.1.

**Comment by durbanlegend** [comment]
Thank you. Looking good in all my environments and terminals, and my crate.
