### ISSUE TITLE
Release stdin if unable to get background

### ISSUE THREAD

**Issue by kunalmohan** [dalance/termbg#5]
termbg should release stdin if unable to get background colour for xterm. Currently, it returns an error, but the thread querying the colour continues to hold onto stdin and runs in the background. This does not let other threads lock on stdin.

**Comment by dalance** [comment]
Thank you for your report.
I tried to change from background thread to async-std to fix it.
Could you try https://github.com/dalance/termbg/commit/fed9852c08737ab86010acc1f577be99388440e6 ?

**Comment by kunalmohan** [comment]
Yeah, its working for me.

**Comment by dalance** [comment]
Thanks! I released v0.3.0.

**Comment by kunalmohan** [comment]
Thanks!!
